name: flutter_bloc_todo
description: Sample todo application using flutter with bloc.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  package_info: ^0.4.0+3
  shared_preferences: ^0.5.2
  flutter_custom_tabs: ^0.6.0
  json_annotation: ^2.2.0
  uuid: ^2.0.1
  bloc_provider: ^0.5.0+3
  rxdart: ^0.21.0
  injector: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.3.1
  json_serializable: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/drawer_header_icon.png
